version: "3.8"
services:
    umerx_blackdog_configurator_frontend:
        build:
            context: ./.devcontainer
            dockerfile: Dockerfile
        command: sleep infinity
        volumes:
            - ./:/workspace
        ports:
            - ${BLACKDOG_CONFIGURATOR_FRONTEND_INTERFACE}:${BLACKDOG_CONFIGURATOR_FRONTEND_PORT}:${BLACKDOG_CONFIGURATOR_FRONTEND_VITE_PORT}
        environment:
            - BLACKDOG_CONFIGURATOR_FRONTEND_VITE_PORT=${BLACKDOG_CONFIGURATOR_FRONTEND_VITE_PORT}

# https://tjtelan.com/blog/how-to-link-multiple-docker-compose-via-network/
# https://containers.dev/guide/dockerfile
# https://github.com/microsoft/vscode-remote-release/issues/2485
networks:
    default:
        external: true
        name: "umerx_blackdog"
