name: Publish Dev
on:
    push:
        branches:
            - main
    workflow_dispatch:
concurrency: "dev_${{ github.ref_name }}"
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        env:
            DOCKER_IMAGE_REPO: ${{ github.repository }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - # Add support for more platforms with QEMU (optional)
              # https://github.com/docker/setup-qemu-action
              name: Set up QEMU
              uses: docker/setup-qemu-action@v3
              with:
                  platforms: all
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Downcase DOCKER_IMAGE_REPO
              run: |
                  echo "DOCKER_IMAGE_REPO=${DOCKER_IMAGE_REPO,,}" >>${GITHUB_ENV};
            - name: Generate Docker image tags
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ env.DOCKER_IMAGE_REPO }}
                  tags: |
                      type=raw,value=dev
            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  platforms: linux/arm64
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  build-args: |
                      ENVIRONMENT=development
